// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file agv.c
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#include "agv.h"

#include <ucdr/microcdr.h>
#include <string.h>

bool OIE_Time_serialize_topic(ucdrBuffer* writer, const OIE_Time* topic)
{
    bool success = true;

        success &= ucdr_serialize_int32_t(writer, topic->sec);

        success &= ucdr_serialize_uint32_t(writer, topic->nanosec);

    return success && !writer->error;
}

bool OIE_Time_deserialize_topic(ucdrBuffer* reader, OIE_Time* topic)
{
    bool success = true;

        success &= ucdr_deserialize_int32_t(reader, &topic->sec);

        success &= ucdr_deserialize_uint32_t(reader, &topic->nanosec);

    return success && !reader->error;
}

uint32_t OIE_Time_size_of_topic(const OIE_Time* topic, uint32_t size)
{
    uint32_t previousSize = size;
        size += ucdr_alignment(size, 4) + 4;

        size += ucdr_alignment(size, 4) + 4;

    return size - previousSize;
}

bool Distance_serialize_topic(ucdrBuffer* writer, const Distance* topic)
{
    bool success = true;

        success &= ucdr_serialize_string(writer, topic->publicName);

        success &= ucdr_serialize_string(writer, topic->system);

        success &= ucdr_serialize_uint32_t(writer, topic->quality);

        success &= OIE_Time_serialize_topic(writer, &topic->timeStamp);
        success &= ucdr_serialize_int32_t(writer, topic->angle);

        success &= ucdr_serialize_double(writer, topic->distance);

    return success && !writer->error;
}

bool Distance_deserialize_topic(ucdrBuffer* reader, Distance* topic)
{
    bool success = true;

        success &= ucdr_deserialize_string(reader, topic->publicName, 255);

        success &= ucdr_deserialize_string(reader, topic->system, 255);

        success &= ucdr_deserialize_uint32_t(reader, &topic->quality);

        success &= OIE_Time_deserialize_topic(reader, &topic->timeStamp);
        success &= ucdr_deserialize_int32_t(reader, &topic->angle);

        success &= ucdr_deserialize_double(reader, &topic->distance);

    return success && !reader->error;
}

uint32_t Distance_size_of_topic(const Distance* topic, uint32_t size)
{
    uint32_t previousSize = size;
        size += ucdr_alignment(size, 4) + 4 + (uint32_t)strlen(topic->publicName) + 1;

        size += ucdr_alignment(size, 4) + 4 + (uint32_t)strlen(topic->system) + 1;

        size += ucdr_alignment(size, 4) + 4;

        size += OIE_Time_size_of_topic(&topic->timeStamp, size);
        size += ucdr_alignment(size, 4) + 4;

        size += ucdr_alignment(size, 8) + 8;

    return size - previousSize;
}

bool TrackSpeed_serialize_topic(ucdrBuffer* writer, const TrackSpeed* topic)
{
    bool success = true;

        success &= ucdr_serialize_string(writer, topic->publicName);

        success &= ucdr_serialize_string(writer, topic->system);

        success &= ucdr_serialize_uint32_t(writer, topic->quality);

        success &= OIE_Time_serialize_topic(writer, &topic->timeStamp);
        success &= ucdr_serialize_double(writer, topic->speedPercent);

    return success && !writer->error;
}

bool TrackSpeed_deserialize_topic(ucdrBuffer* reader, TrackSpeed* topic)
{
    bool success = true;

        success &= ucdr_deserialize_string(reader, topic->publicName, 255);

        success &= ucdr_deserialize_string(reader, topic->system, 255);

        success &= ucdr_deserialize_uint32_t(reader, &topic->quality);

        success &= OIE_Time_deserialize_topic(reader, &topic->timeStamp);
        success &= ucdr_deserialize_double(reader, &topic->speedPercent);

    return success && !reader->error;
}

uint32_t TrackSpeed_size_of_topic(const TrackSpeed* topic, uint32_t size)
{
    uint32_t previousSize = size;
        size += ucdr_alignment(size, 4) + 4 + (uint32_t)strlen(topic->publicName) + 1;

        size += ucdr_alignment(size, 4) + 4 + (uint32_t)strlen(topic->system) + 1;

        size += ucdr_alignment(size, 4) + 4;

        size += OIE_Time_size_of_topic(&topic->timeStamp, size);
        size += ucdr_alignment(size, 8) + 8;

    return size - previousSize;
}
